import { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import About from '../components/About'
import Contact from '../components/Contact'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import WorkExperience from '../components/WorkExperience'
import pageinfo from '../sanity/schemas/pageinfo'
import { Experience, PageInfo, Project, Skill, Social } from '../typings'
import { fetchExperiences } from '../utils/fetchExperiences'
import { fetchPageInfo } from '../utils/fetchPageInfo'
import { fetchProjects } from '../utils/fetchProjects'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchSocials } from '../utils/fetchSocials'

type Props = {
  pageInfo: PageInfo;
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[]
}

export default function Home({pageInfo, experiences,skills,projects,socials}: Props) {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll 
    overflow-hidden  z-0 scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]'>
      <Head>
        <title>Habeeb's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* Header  */}
    <Header socials={socials}/>
    {/* Hero  */}
    <section id='hero'>
      <Hero pageInfo={pageInfo}/>
    </section>

    {/* About  */}

    <section id="about" className='snap-start'>
        <About pageInfo={pageInfo}/>
    </section>

    {/* Experience  */}
      <section className='' id="experience">
        <WorkExperience experiences={experiences}/>
      </section>

    {/* Skills  */}

    <section id="skills">
    <Skills skills={skills}/>
    </section>

    {/* Projects  */}

    <section id="projects">
      <Projects projects={projects}/>
    </section>

    {/* Contact me  */}

    <section id="contact" className=''>
      <Contact />
    </section>
    </div>
  )
}

export const  getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const experiences: Experience[] = await fetchExperiences();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();
  const socials: Social[] = await fetchSocials();

  return {
    props: {
      pageInfo,
      experiences,
      skills,
      projects,
      socials,
    },

    // Next.js will attempt to re-generate the page
    // -When a request comes in
    // -At most once every 10 seconds 
    revalidate: 10
  }
}

